GET http://localhost:4000/day

###

POST http://localhost:4000/day
Content-Type: application/json

{
  "day" : "2020-01-17",
  "mood" :"Great"
}

###

GET http://localhost:4000/day/2020-01-17T00:00:00.000Z

###

DELETE http://localhost:4000/day/2020-01-17T00:00:00.000Z